### PR TITLE
N-Queens Problem Test

### LINKED ISSUE #4: N-Queens Problem Testcase

### PR DESCRIPTION
**Pull request by alexsc23**
Review please

### CODE REVIEW

**Review by xTomsko — APPROVED** [review]
approved

**Comment by TheMuppet** [comment]
I refactored the csp layout in #7. Please adjust the current changes and make sure the automatic tests are working

**Review by xTomsko — APPROVED** [review]
approved

**Comment by xTomsko** [comment]
locally the Deno error does not occur, maybe flase-positve. needs to be checked by second reviewer @TheMuppet

**Comment by TheMuppet** [comment]
> locally the Deno error does not occur, maybe flase-positve. needs to be checked by second reviewer @TheMuppet
Fixed It

**Comment by TheMuppet** [comment]
With the test the answer of the csp is not really checked. Please implement a function that verifies the result. The function will be helpful in the future once we implement other solvers.

**Review by TheMuppet — APPROVED** [review]

**Review by xTomsko — APPROVED** [review]

**Pull request merged**
